// <auto-generated />
using LGX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LGX.Migrations
{
    [DbContext(typeof(LGXContext))]
    [Migration("20210812191723_LocalDB")]
    partial class LocalDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LGX.Models.RelayRack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("Isle");

                    b.Property<string>("Name");

                    b.Property<string>("RackNumber");

                    b.HasKey("Id");

                    b.ToTable("RelayRack");
                });

            modelBuilder.Entity("LGX.Models.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceType");

                    b.Property<int>("RelayRackId");

                    b.HasKey("Id");

                    b.HasIndex("RelayRackId");

                    b.ToTable("Shelf");
                });

            modelBuilder.Entity("LGX.Models.Shelf", b =>
                {
                    b.HasOne("LGX.Models.RelayRack", "RelayRack")
                        .WithMany()
                        .HasForeignKey("RelayRackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
